<div style="position: absolute; margin: -100px 0 0 100px;">
<div id="ex3c" class="jqmNotice">
    <div class="jqmnTitle jqDrag">
    	<h1>Did you know?</h1>
    </div>
	
	<div class="jqmnContent">
	<p>Pine, spruce, or other evergreen wood should never be used in barbecues. These woods, when burning or smoking, can add harmful tar and resins to the food. Only hardwoods should be used for smoking and grilling, such as oak, pecan, hickory, maple, cherry, alder, apple, or mesquite, depending on the type of meat being cooked.</p>
	</div>
	
	<img src="notice/close_icon.png" alt="close" class="jqmClose" />
	<img src="dialog/resize.gif" alt="resize" class="jqResize" />
</div>
</div>