<!-- Alert Dialog -->
<div class="jqmAlert" id="alert">

<div id="ex3b" class="jqmAlertWindow">
    <div class="jqmAlertTitle clearfix">
		<h1>Warning!</h1><a href="#" class="jqmClose"><em>Close</em></a>
	</div>
	
	<div class="jqmAlertContent"></div>
</div>

</div>



<!-- Confirm Dialog -->
<div class="jqmConfirm" id="confirm">

<div id="ex3b" class="jqmConfirmWindow">
    <div class="jqmConfirmTitle clearfix">
		<h1>Confirmation por favor...</h1><a href="#" class="jqmClose"><em>Close</em></a>
	</div>
	
	<div class="jqmConfirmContent">
	<p class="jqmConfirmMsg"></p>
	<p>Continue?</p>
	</div>
	
	<input type="submit" value="no" />
	<input type="submit" value="yes" />
	</p>
	
</div>

</div>